### ISSUE TITLE
Queries related to calculation of Tajima's D value

### ISSUE THREAD

**Issue by Rohit-Satyam** [hemstrow/snpR#55]
Hi @hemstrow 

Thanks for making this wonderful package and I am glad i stumbled upon it. I have some queries because I couldn't find anything on Tajima in the vignette. So apologies!! So I have a set of genes (that encodes exported proteins) and I have Plasmodium pf7K dataset which comprise of variants from ~20800 plasmodium genomes collected from 34 countries over a period of 2 decades. 

Now the question we are trying to answer is "are our genes of interest evolving or are conserved". For this we first get the coordinates for our genes from GFF file and then subset the VCF for the genic region only (since loading the entire genome VCF will take forever in R. My queries are:
 
1. Should I pre filter the VCF files for low quality variants or not based on MAF or VQSR scores? I am hesitant to do it since it might introduce bias as described [here](https://github.com/ANGSD/angsd/issues/236). But I observe that people do it all the time in population studies. So what's the standard practice? (Note: Filtering or no-filtering global TD values for my genes stays negative, only magnitude changes) 
2. When calculating TajimasD value, what will you recommend `sliding window` or `bins`.
3. My VCF file is SNPEFF annotated and I was hoping to calculate TajimasD value for synonymous and nonsynonymous SNPs separately. But for some reason, such information is not included in the Facet section of `snpRdata` object.

```
> vcf@stats
     facet subfacet facet.type       CHROM position   ID REF ALT    QUAL FILTER .snp.id
  1: .base    .base      .base Pf3D7_09_v3  1201344 <NA>   T   C  153.71   PASS       1
  2: .base    .base      .base Pf3D7_09_v3  1201369 <NA>   A   T  268.25   PASS       2
  3: .base    .base      .base Pf3D7_09_v3  1201371 <NA>   A   G    3488   PASS       3
  4: .base    .base      .base Pf3D7_09_v3  1201492 <NA>   T   C 26771.3   PASS       4
  5: .base    .base      .base Pf3D7_09_v3  1201505 <NA>   G   A   57.03   PASS       5
 ---                                                                                   
592: .base    .base      .base Pf3D7_09_v3  1207438 <NA>   A   C 1830.62   PASS     592
593: .base    .base      .base Pf3D7_09_v3  1207516 <NA>   T   A 12364.5   PASS     593
594: .base    .base      .base Pf3D7_09_v3  1207543 <NA>   A   T 3136.44   PASS     594
595: .base    .base      .base Pf3D7_09_v3  1207545 <NA>   T   A  2586.6   PASS     595
596: .base    .base      .base Pf3D7_09_v3  1207547 <NA>   A   C 13797.3   PASS     596
     major minor maj.count min.count          maf
  1:     T     C     36620         2 5.461198e-05
  2:     A     T     36118         4 1.107358e-04
  3:     A     G     36132        18 4.979253e-04
  4:     T     C     34325        41 1.193040e-03
  5:     G     A     33195         3 9.036689e-05
 ---                                             
592:     A     C     37111         3 8.083203e-05
593:     T     A     37776        18 4.762661e-04
594:     A     T     37787         7 1.852146e-04
595:     T     A     37673         5 1.327034e-04
596:     A     C     37733        35 9.267104e-04
```

```r
> snpR::summarize_facets(vcf)
Returning list of facets. For more details, try asking for information about a specific facet (such as 'pop' or 'pop.chr')!
$SNP
[1] "CHROM"    "position" "ID"       "REF"      "ALT"      "QUAL"     "FILTER"   ".snp.id" 

$sample
[1] "sampID"     ".sample.id"
```
4. Do you have any recommendations on how to handle multiallelic sites in a multisample VCF files since bcftools fails and gives segmentation fault (already raised the issue [here](https://github.com/samtools/bcftools/issues/2020). Does your function take into account such sites (I can see only biallelic sites are considered so far? Also can you confirm if I am running snpR in correct way

```r
vcf<-read_vcf("PF3D7_0930300.vcf")

## Get Global TD vale for the gene
td<-calc_tajimas_d(vcf, global = TRUE)
res<-get.snpR.stats(td, facets = ".base", stats = "tajimas_d")$single.window

## Get TD value per 10bp (since this gene is barely 2KB long)
td<-calc_tajimas_d(vcf, sigma = 0.01, step =0.01) 
res<-get.snpR.stats(td, facets = ".base", stats = "tajimas_d")$single.window
```
5. When we calculate the global tajimasD value, does your function also provide `95% confidence interval` like I see in [this paper ](https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1008191). 
6. Finally, there are some samples where the genotype information is missing `./.`. Like vcftools, does `snpR::calc_tajimas_d` ignores such sites? Should I replace it with `0/0` like suggested in this [biostar ](https://www.biostars.org/p/410300/)post?

I am sorry but these small details are never discussed and might impact the values calculated

**Comment by hemstrow** [comment]
Hey @Rohit-Satyam , glad to hear you are liking the package!

1. You are absolutely correct to be cautious in filtering low frequency variants when calculating Tajima's D, since doing so can cause a substantial positive bias in results. My usual approach is to use a very slight filter--something like singleton removal (which you can do with `mgc = 1` or `mac = 1` depending on your preference, see the documentation for `filter_snps()`) is a good call to remove a decent batch of things that are more likely to be sequencing errors without introducing much bias. I'm not sure exactly what bias using VQSR might present--if you are concerned I'd run it both with and without. I and a few co-authors actually currently have a big paper in revision that deals with filtering choices like this!

2. I generally use sliding windows for Tajima's D, with the window size depending on the scale at which you are looking for effects. Something like `calc_tajimas_d(mydat, facets = "pop.chr", sigma = 50, triple_sigma = FALSE, step = 100)` will give you 100kb non-overlapping windows, for example.

3. Import from `vcf` files is currently handled with the `vcfR` package, and it may not support the field you are storing annotations in. That said, it's pretty reasonable to add them back (which is what I've done before) using something like this:

```{r}
meta <- data.table::fread("my_snp_effects.txt")
snp.meta(mydat)$eff <- meta$effect
```
which will add a new metadata column in. Unfortunately `snpR` could stand to be optimized here, so this process is a bit slower than updating with new sample metadata using the equivalent function, but it should work just fine. Let me know if you have issues with this, I'm happy to help.

4. I've been gradually working on supporting non-biallelic markers. It's been pretty easy to implement for some functions but quite a bit more time consuming for others and is still very much in development. For now it'll automatically filter non-biallelic markers out during import. Tajima's D isn't done yet, I'm afraid. I'm hoping to have some time to finish enough of the package that I feel comfortable releasing it sometime next year.

5. Not at the moment, but if that is something you are interested in I could potentially look into it. That said, I suspect this is something that shouldn't be too hard to do manually by resampling the Tajima's D values that you can produce or by resampling your SNPs and running Tajima's D each time depending on the level you want to bootstrap at.

6. `snpR` is fine with missing data for Tajima's D--no imputation or anything. It'll ignore missing data when calculating the thetas/variances, since it's using tables of allele counts to do so.

Please let me know if you have any other questions or run into issues, I'm happy to help!

**Comment by Rohit-Satyam** [comment]
Hi @hemstrow. Thanks for taking out time to answer my queries.  

>I'm not sure exactly what bias using VQSR might present--if you are concerned I'd run it both with and without. I and a few co-authors actually currently have a big paper in revision that deals with filtering choices like this!

I was referring to VQSLOD score (when I said VQSR scores since they were calculated during VQSR step) and maybe this is restricted to the dataset I am handling but the MalariaGen Pf7K supplementary an README [here](https://www.malariagen.net/sites/default/files/Pf7_README_20221021.txt) says:

>Variants are filtered using the VQSLOD metric. VQSLOD is log(p/q) where p is the
probability of being true and q is the probability of being false. Theoretically,
when VQSLOD > 0, p is greater than q, and therefore the variant is more likely
true than false. Conversely, when VQSLOD < 0, the variant is theoretically more
like false than true. This is why we have chosen 0 as the threshold to use to
declare that variants have passed the filters: all PASS variants are
theoretically more likely true than false. Of course, for variants where VQSLOD
is only slightly above 0, there is only a slightly greater probability of being
true than of being false. Therefore, for example, many of the variants with
values between 0 and 1 are likely to be false.
Empirically we have found that SNPs tend to be more accurate than indels, coding
variants tend to be more accurate than non-coding variants, and bi-allelic
variants tend to be more accurate than multi-allelic variants. If you require a
very reliable set of variants for genome-wide analysis, and don't mind if you
miss some real variants, we recommend using only bi-allelic coding SNPs in the
core genome with a VQSLOD score > 6. There are 83,168 such stringent SNPs in the
call set. We include a command below to create such a set of variants.

>I and a few co-authors actually currently have a big paper in revision that deals with filtering choices like this!

I am looking forward to read that paper if and when it comes out. Please include a link to it in the README of `snpR` once it is available.

**Comment by hemstrow** [comment]
@Rohit-Satyam 

Hmm, I'm not sure how or if that'd systematically bias Tajima's D. It depends on if p/q values tend to be biased depending on allele frequencies, I believe. If not, then I'd guess you shouldn't generally see any serious bias by using this filter. Again, I'd recommend just running with and without as a check and if you don't see any serious shift in D you can probably not worry about it too much!

**Comment by Rohit-Satyam** [comment]
@hemstrow 
> I and a few co-authors actually currently have a big paper in revision that deals with filtering choices like this!
 
Is the collaborative paper that you mentioned out on any preprint? I am still eagerly waiting to read it to finalize my results and tick all the boxes.

**Comment by hemstrow** [comment]
@Rohit-Satyam It's currently in review! We're hoping it'll come out soon--if you'd like to see an early draft we could potentially do that.

**Comment by Rohit-Satyam** [comment]
@hemstrow Yes, please. That would be so helpful. My email ID is rohit.satyam@kaust.edu.sa
