### ISSUE TITLE
calc_pairwise_ld

### ISSUE THREAD

**Issue by WickEmm** [hemstrow/snpR#63]
Hi again,

ON the same dataset (the RDS one),  I just had a surprising error: 
My code: 
tr4.dat10<-calc_pairwise_ld(tr4.dat10,
+                              facets=c("SC_DAPC","SC_DAPC.Year_range", "SC_DAPC.Geo_Region"),
+                              par=4,
+                              sigma=1e-04,
+                              window_sigma = 50,
+                              window_step=100,
+                              window_triple_sigma = FALSE)
REPLY:
Erreur dans data.table::rbindlist(out) : 
  Unsupported column type in assign.c:memrecycle 'language'

**Comment by hemstrow** [comment]
Well that's an interesting one! I can take a look later today. Thanks again
for the report!

**Comment by WickEmm** [comment]
I think I was wrong in the facets chosen... Testing with facets="SC_DAPC.CHROM" only, it worked. In the former facets I did not declare the chromosomes..
Sorry

**Comment by hemstrow** [comment]
OK, I think I've figured the problem out--it was due to some errors during object returns when there were windows with SNPs, but none of which are polymorphic in a given facet level. Since this is a slightly more niche bug, I just pushed it to the 'dev' branch to hold it for the next major release. You can install the dev branch with:

`remotes::install_github("hemstrow/snpR", ref = "dev")`

Thanks again for the report! Not using a snp-level facet is supposed to work fine, so it was definitely a bug.
