### ISSUE TITLE
request: bootstrap confidence intervals 

### ISSUE THREAD

**Issue by rsbrennan** [hemstrow/snpR#68]
Hi Will, 

I'm using calc_fis to get FIS values. Could the confidence intervals from the bootstrapping be returned? Instead of the p-values comparing to 0. I'm more interested in comparing populations than comparing to zero. 

Similarly, it'd be nice if calc_ho, calc_he, could run bootstrapping and return CIs. 

Thanks.
Reid

**Comment by hemstrow** [comment]
Hey @rsbrennan,

This is potentially doable, although it's going to take a bit of coding to implement for most other statistics. $F_{IS}$ is much easier since the bootstrapping framework is already there--I just pushed an update to `calc_fis()` on the dev branch which includes CIs in the output.

You can install the dev branch and run with

```{r}
remotes::install_github("hemstrow/snpR", ref = "dev")
library(snpR)
x <- calc_fis(stickSNPs, "pop", boot = 10)
get.snpR.stats(x, "pop", "fis")$weighted.means
```
You should see the columns `weighted_mean_fis_uCI` and `weighted_mean_fis_lCI` in output! You can adjust the confidence level with the `boot_confidence` arg.

Let me know if you have issues with it!

**Comment by rsbrennan** [comment]
yep. that works. thanks for the fast fix!
